global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pdf-service'
    static_configs:
      - targets: ['pdf-service:3000']
    metrics_path: /metrics

  - job_name: 'docker-stats'
    static_configs:
      - targets: ['stats-exporter:8080'] 